eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8760

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://gitlab.centit.com/gitlab/ctm/spring-cloud-demo/
          search-paths: respo
          username: accounts
          password: yhs@yhs1